name: unila_aqi
description: UNILA Air Quality Index Monitoring System
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  socket_io_client: ^2.0.3
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_svg: ^2.0.10
  fl_chart: ^0.66.0
  cached_network_image: ^3.3.0
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.1
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_unila.png
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700